pipeline {
    // agent {
    //     docker {
    //         image 'maven:3.5.4-alpine'
    //         args '-v /root/.m2:/root/.m2'
    //     }
    // }
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    app = docker.build("kwbriggs/capstone")
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
